export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";
export const LOGOUT = "LOGOUT";
export const SET_ONBOARDING = "SET_ONBOARDING";
export const SET_PICTURE = "SET_PICTURE";
export const UPDATE_SUCCESS = "UPDATE_SUCCESS";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const GET_NOTIFICATIONS_REQUEST = "GET_NOTIFICATIONS_REQUEST";
export const GET_NOTIFICATIONS_SUCCESS = "GET_NOTIFICATIONS_SUCCESS";
export const GET_NOTIFICATIONS_ERROR = "GET_NOTIFICATIONS_ERROR";
export const INCOMING_NOTIFICATION = "INCOMING_NOTIFICATION";
export const ACCEPT_CONN_REQUEST = "ACCEPT_CONN_REQUEST";
export const ACCEPT_PROJECT_REQUEST = "ACCEPT_PROJECT_REQUEST";
export const ACCEPT_REQUEST = "ACCEPT_REQUEST";

export const GET_FEED_REQUEST = "GET_FEED_REQUEST";
export const GET_FEED_SUCCESS = "GET_FEED_SUCCESS";
export const GET_FEED_ERROR = "GET_FEED_ERROR";

export const GET_FOLL_FEED_REQUEST = "GET_FOLL_FEED_REQUEST";
export const GET_FOLL_FEED_SUCCESS = "GET_FOLL_FEED_SUCCESS";
export const GET_FOLL_FEED_ERROR = "GET_FOLL_FEED_ERROR";
